name: Sync Fork

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  sync:
    name: Sync fork with upstream
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write # Required to push merged upstream changes
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Pull upstream changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote add upstream https://github.com/google/nsjail.git
          git pull --no-rebase upstream master
          git push origin master
